version: 0.2
phases:
  build:
    commands:
      - nvidia-smi
      - pwd
      - cd /src/ksim/mjx_gym
      - |
        python3 play.py \
        --config experiments/default_humanoid_walk.yaml \
        --use_mujoco
      # rename videos using date and enumerate them
      - export DATE=$(date +%Y.%m.%d)
      - |
        for file in *.mp4; do
          NEW_NAME="${DATE}.ksim.mp4"
          mv "$file" "$NEW_NAME"
        done
      # Create yml file with metadata (github commit, date, name, environment)
      - |
        METADATA_FILE="${DATE}.ksim.yml"
        NAME="play.py experiments/default_humanoid_walk.yaml"
        echo "name: $NAME" >> "$METADATA_FILE"
        echo "date: $DATE" >> "$METADATA_FILE"
        ENV="PickCube-v1"
        echo "env: $ENV" >> "$METADATA_FILE"
        GIT_REPO=$(git config --get remote.origin.url)
        GIT_HASH=$(git rev-parse HEAD)
        echo "git: $GIT_REPO" >> "$METADATA_FILE"
        echo "hash: $GIT_HASH" >> "$METADATA_FILE"
artifacts:
  files:
    - ./*.mp4
    - ./*.yml
  discard-paths: yes
