version: 0.2
phases:
  build:
    commands:
      - nvidia-smi
      - pwd
      - cd /src/ksim/mjx_gym
      - |
        python3 play.py \
        --config experiments/stompy_walk.yaml \
        --params_path=weights/stompy_walk.pkl \
        --use_mujoco
      # rename video using date
      - export DATE=$(date +%Y.%m.%d)
      - mv video.mp4 "${DATE}.ksim.mp4" 
      # Create yml file with metadata (github commit, date, name, environment)
      - |
        METADATA_FILE="${DATE}.ksim.yml"
        NAME="mjx_gym/play.py experiments/default_humanoid_walk.yaml weights/stompy_walk.pkl"
        echo "name: $NAME" >> "$METADATA_FILE"
        echo "date: $DATE" >> "$METADATA_FILE"
        ENV="PickCube-v1"
        echo "env: $ENV" >> "$METADATA_FILE"
        GIT_REPO=$(git config --get remote.origin.url)
        GIT_HASH=$(git rev-parse HEAD)
        echo "git: $GIT_REPO" >> "$METADATA_FILE"
        echo "hash: $GIT_HASH" >> "$METADATA_FILE"
artifacts:
  files:
    - /src/ksim/mjx_gym/*.ksim.mp4
    - /src/ksim/mjx_gym/*.ksim.yml
  discard-paths: yes
