version: 0.2
phases:
  build:
    commands:
      - nvidia-smi
      # downgrade torch for compatibility with CUDA 11.4
      - python -c "import torch; print('PyTorch Version:', torch.__version__)"
      - pip install torch==2.2.0 torchvision==0.17.0 torchaudio==2.2.0 --index-url https://download.pytorch.org/whl/cu118
      - python -c "import torch; print('PyTorch Version:', torch.__version__)"
      - |
        python -m mani_skill.examples.benchmarking.gpu_sim \
        -e "PickCube-v1" \
        -n 64 \
        --save-video \
        --render-mode="sensors"
      - cd ./videos/benchmark/
      # rename videos using date and enumerate them
      - export DATE=$(date +%Y.%m.%d)
      - |
        COUNT=1
        for file in *.mp4; do
          NEW_NAME=$(printf "%s.maniskill.%02d.mp4" "$DATE" "$COUNT")
          mv "$file" "$NEW_NAME"
          COUNT=$((COUNT + 1))
        done
      # Create yml file with metadata (github commit, date, name, environment)
      - |
        METADATA_FILE="${DATE}.maniskill.yml"
        NAME="mani_skill.examples.benchmarking.gpu_sim"
        ENV="PickCube-v1"
        COMMIT_HASH=$(git rev-parse HEAD)
        echo "name: $NAME" >> "$METADATA_FILE"
        echo "env: $ENV" >> "$METADATA_FILE"
        echo "commit: $COMMIT_HASH" > "$METADATA_FILE"
        echo "date: $DATE" >> "$METADATA_FILE"
artifacts:
  files:
    - videos/benchmark/*.mp4
    - videos/benchmark/*.yml
  discard-paths: yes
