version: 0.2
phases:
  install:
    commands:
      - echo pulling docker image from ecr
      - docker pull public.ecr.aws/v6x3n6y1/eval:maniskill
  build:
    commands:
      - echo running docker container
      - |
        docker run \
        -v $(pwd)/videos:/app/videos \
        eval:maniskill \
        python -m mani_skill.examples.demo_random_action \
        -e PickCube-v1 \
        --env_id="PickCube-v1" \
        --render-mode="rgb_array" \
        --record-dir="videos" \
        --num_envs=1
  post_build:
    commands:
      - echo eval completed on `date`
artifacts:
  files:
    - videos/*.mp4
