version: 0.2
phases:
  pre_build:
    commands:
      - echo pulling docker image from ecr
      - docker pull public.ecr.aws/v6x3n6y1/kscale-eval:sim
  build:
    commands:
      - echo running docker container
      - |
        docker run \
        -v $(pwd)/videos:/app/videos \
        public.ecr.aws/v6x3n6y1/kscale-eval:sim \
        python sim/humanoid_gym/play.py \
        --task legs_ppo \
        --sim_device cpu
  post_build:
    commands:
      - echo eval completed on `date`
artifacts:
  files:
    - videos/*.mp4
