version: 0.2
phases:
  build:
    commands:
      - nvidia-smi
      - python -c "import torch; print('PyTorch Version:', torch.__version__)"
      - pip install torch==2.2.0 torchvision==0.17.0 torchaudio==2.2.0 --index-url https://download.pytorch.org/whl/cu118
      - python -c "import torch; print('PyTorch Version:', torch.__version__)"
      - |
        python -m mani_skill.examples.benchmarking.gpu_sim \
        -e "PickCube-v1" \
        -n 64 \
        --save-video \
        --render-mode="sensors"
artifacts:
  files:
    - videos/*.mp4
