version: 0.2
phases:
  build:
    commands:
      - nvidia-smi
      - echo running docker container
      - |
        python -m mani_skill.examples.benchmarking.gpu_sim \
        -e "PickCube-v1"
        -n 64 \
        --save-video \
        --render-mode="sensors"
artifacts:
  files:
    - videos/*.mp4
