name: eval sim
on:
  schedule:
    - cron: '0 0 * * 5'  # Runs every Friday at midnight UTC
  workflow_dispatch:  # Manually trigger the workflow

jobs:
  build-docker-run-eval-publish-video:
    name: build docker container and evaluate model
    runs-on: ubuntu-latest
    steps:
      - name: configure aws credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1 # public registries are only available in us-east-1

      - name: Login to Amazon ECR Public
        id: login-ecr-public
        uses: aws-actions/amazon-ecr-login@v2
        with:
          registry-type: public

      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          repository: "hu-po/sim"

      - name: Build, tag, and push docker image to Amazon ECR Public
        env:
          REGISTRY: ${{ steps.login-ecr-public.outputs.registry }}
          REGISTRY_ALIAS: v6x3n6y1
          REPOSITORY: kscale-eval
          IMAGE_TAG: sim
        run: |
          docker build -t $REGISTRY/$REGISTRY_ALIAS/$REPOSITORY:$IMAGE_TAG -f docker/Dockerfile.eval .
          docker push $REGISTRY/$REGISTRY_ALIAS/$REPOSITORY:$IMAGE_TAG

      - name: configure aws credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-2 # kscale codebuild project is on us-east-2

      - name: run codebuild
        uses: aws-actions/aws-codebuild-run-build@v1
        with:
          project-name: eval
          disable-source-override: true
          buildspec-override: buildspec.sim.yml
          compute-type-override: BUILD_GENERAL1_LARGE
          environment-type-override: LINUX_GPU_CONTAINER
