name: eval maniskill
on:
  workflow_dispatch:  # manually trigger the workflow
  schedule:
    - cron: '0 0 * * 5'  # runs every Friday at midnight UTC
jobs:
  eval-maniskill:
    name: eval maniskill
    runs-on: ubuntu-latest
    steps:
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-2
      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          repository: "kscalelabs/ManiSkill"
      - name: Build, tag, and push docker image to Amazon ECR
        env:
          REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          REPOSITORY: dpsh-eval
          IMAGE_TAG: maniskill
        run: |
          cd docker 
          docker build -t $REGISTRY/$REPOSITORY:$IMAGE_TAG -f Dockerfile .
          docker push $REGISTRY/$REPOSITORY:$IMAGE_TAG
      - name: Run CodeBuild
        uses: aws-actions/aws-codebuild-run-build@v1
        with:
          project-name: eval
          disable-source-override: true
          buildspec-override: buildspec.maniskill.yml
          compute-type-override: BUILD_GENERAL1_LARGE
          environment-type-override: LINUX_GPU_CONTAINER
          image-override: 339713082920.dkr.ecr.us-east-2.amazonaws.com/dpsh-eval:maniskill
      - name: Set DATE environment variable
        run: echo "DATE=$(date +%Y.%m.%d)" >> $GITHUB_ENV
      - name: Generate S3 PreSigned URL
        uses: anton-yurchenko/s3-pre-signed-url@v1
        id: s3-metadata
        with:
          access_key: ${{ secrets.AWS_ACCESS_KEY_ID }}
          secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          region: us-east-2
          bucket: dpsh-eval
          path: eval/${{ env.DATE }}.maniskill.yml
      - name: Generate S3 PreSigned URL
        uses: anton-yurchenko/s3-pre-signed-url@v1
        id: s3-video
        with:
          access_key: ${{ secrets.AWS_ACCESS_KEY_ID }}
          secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          region: us-east-2
          bucket: dpsh-eval
          path: eval/${{ env.DATE }}.maniskill.mp4
      - name: Download video
        run: curl -o "${{ env.DATE }}.maniskill.mp4" "${{ steps.s3-video.outputs.url }}"
      - name: Download metadata into environment variable
        run: |
          curl -o "${{ env.DATE }}.maniskill.yml" "${{ steps.s3-metadata.outputs.url }}"
          echo METADATA=$(cat "${{ env.DATE }}.maniskill.yml") >> $GITHUB_ENV
      - name: Discord Webhook Action
        uses: tsickert/discord-webhook@v5.3.0
        with:
          webhook-url: ${{ secrets.WEBHOOK_URL }}
          content: "```yaml\n${{ env.METADATA }}\n```"
          filename: ${{ env.DATE }}.maniskill.mp4
